[server]
headless = true
enableCORS = false
enableXsrfProtection = true

[theme]
base = "dark"
backgroundColor = "#020817"
secondaryBackgroundColor = "#0f172a"
textColor = "#f1f5f9"
primaryColor = "#3b82f6"
